export let mockCandidatesDb: any[] = [
  {
    id: 'cand_001',
    fullName: 'Carlos Mendoza',
    email: 'carlos.mendoza@ejemplo.com',
    phone: '+525512345678',
    city: 'Ciudad de México',
    hasCar: true,
    financialBufferMonths: 4,
    commissionOnly: true,
    salesExperienceYears: 5,
    background: 'Banca',
    targetUniversity: 'Tec de Monterrey',
    highNetWorthAccess: true,
    notes: 'Ex-ejecutivo de banca patrimonial con cartera activa de empresarios en zona Santa Fe.',
    score: 95,
    status: 'GREEN',
    reviewStatus: 'APPROVED',
    aiAnalysis: '🟢 CANDIDATO IDEAL: Cumple al 100% los Filtros de Hierro. Posee auto, 4 meses de respaldo y red HNW.',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'cand_002',
    fullName: 'Mariana Ríos',
    email: 'mariana.rios@ejemplo.com',
    phone: '+525587654321',
    city: 'Guadalajara',
    hasCar: false,
    financialBufferMonths: 3,
    commissionOnly: true,
    salesExperienceYears: 4,
    background: 'Inmobiliaria',
    targetUniversity: 'ITESO / Universidad de Prestigio',
    highNetWorthAccess: true,
    notes: 'Excelente vendedora de desarrollo residencial de alto valor. Vendió su auto recientemente.',
    score: 78,
    status: 'YELLOW',
    reviewStatus: 'PENDING',
    manualReviewReason: 'REVISIÓN MANUAL RECOMENDADA: No cuenta con auto propio actualmente, pero califica por EXCEPCIÓN debido a: Acceso a Mercado Alto / Contactos de Alto Valor, Universidad de Prestigio.',
    aiAnalysis: '🟡 CASO EXCEPCIONAL: Sin auto propio pero con mercado alto HNW y background inmobiliario de lujo.',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'cand_003',
    fullName: 'Roberto Gómez',
    email: 'roberto.gomez@ejemplo.com',
    phone: '+525599887766',
    city: 'Monterrey',
    hasCar: false,
    financialBufferMonths: 1,
    commissionOnly: false,
    salesExperienceYears: 1,
    background: 'Otro',
    targetUniversity: '',
    highNetWorthAccess: false,
    notes: 'Busca sueldo base inicial mientras se capacita.',
    score: 25,
    status: 'RED',
    reviewStatus: 'REJECTED',
    manualReviewReason: 'Buscando sueldo fijo y respaldo financiero insuficiente (1 mes).',
    aiAnalysis: '🔴 CANDIDATO DESCARTADO: No cumple con la aversión al sueldo fijo ni respaldo financiero mínimo.',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  }
];

export let mockUsersDb: any[] = [
  {
    id: 'user_001',
    name: 'Director de Promotoría AACOM',
    email: 'admin@aacom.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    mustChangePassword: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_002',
    name: 'Sofía Reclutadora',
    email: 'sofia.recruiter@aacom.com',
    role: 'RECRUITER',
    status: 'ACTIVE',
    mustChangePassword: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_003',
    name: 'Jorge Asesor Sr',
    email: 'jorge.asesor@aacom.com',
    role: 'RECRUITER',
    status: 'SUSPENDED',
    mustChangePassword: false,
    createdAt: new Date().toISOString(),
  }
];

export let mockIntegrationsDb = {
  twilio: {
    accountSid: process.env.TWILIO_ACCOUNT_SID || 'AC_mock_twilio_account_sid_123',
    authToken: process.env.TWILIO_AUTH_TOKEN ? '••••••••••••••••' : 'mock_auth_token_456',
    fromPhone: process.env.TWILIO_SMS_NUMBER || '+18005550199',
    adminNotifyPhone: process.env.TWILIO_ADMIN_NOTIFY_PHONE || '+525512345678',
    isEnabled: true,
  },
  gemini: {
    apiKey: process.env.GEMINI_API_KEY ? '••••••••••••••••' : 'AIzaSy_mock_gemini_key_789',
    model: 'gemini-1.5-flash',
    isEnabled: true,
  },
};
